version: '3'

services:
  db:
    image: postgres:9.6@sha256:9d8deca17591f6fef6b2c338fee1a5d7c96da99f18bd51149440099239085800
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 1s
      timeout: 3s
      retries: 30
  memcached:
    image: memcached:1.5.9


  autograph:
    build:
      context: autograph
      dockerfile: Dockerfile
    image: kinto:autograph

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: kinto:build
    depends_on:
      - db
      - memcached
      - autograph
    environment:
      - KINTO_STORAGE_URL=postgres://postgres@db/postgres
      - KINTO_PERMISSION_URL=postgres://postgres@db/postgres
      - KINTO_SIGNER_AUTOGRAPH_SERVER_URL=http://autograph:8000
      - KINTO_ATTACHMENT_BASE_URL=http://autograph:8000
      - KINTO_CACHE_BACKEND=kinto.core.cache.memcached
      - KINTO_CACHE_HOSTS=memcached:11211
    ports:
      - "8888:8888"
      - "9999:9999"
    volumes:
      - $PWD:/app
    command: uwsgistart

  tests:
    build:
      context: .
      dockerfile: tests/Dockerfile
    image: kinto:tests
    depends_on:
      - web
    environment:
      - SERVER=http://web:8888/v1
      - MAILFILESERVER=http://web:9999
    volumes:
      - $PWD/tests:/app
      - $PWD/mail:/app/mail/
    command: start
